//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by rez.rc
//
#define IDI_ICON1                       101
#define IDR_MENU1                       105
#define IDR_ACCELERATOR1                107
#define IDD_EDLIGHT                     108
#define IDD_PACKVIEW                    110
#define IDR_BFZPOPUP                    111
#define IDD_IMPBRUSH                    115
#define IDD_NEWBOX                      116
#define IDD_NEWSPHERE                   117
#define IDD_NEWCYL                      118
#define IDD_SURFPROP                    119
#define IDD_WORKING                     120
#define IDD_EDOBJ                       121
#define IDD_PROPBOX                     123
#define IDD_ITEMVIEW                    124
#define IDR_MAINPOP                     125
#define IDC_SELCUR                      126
#define IDC_MOVECUR                     128
#define IDC_CURSOR1                     130
#define IDC_LATROTCUR                   130
#define IDC_ENABLED                     1000
#define IDC_NEGATIVE                    1001
#define IDC_DYNAMIC                     1002
#define IDC_NOLMS                       1003
#define IDC_LUMENS                      1004
#define IDC_INTENSITY                   1005
#define IDC_LTYPE                       1007
#define IDC_LNAME                       1008
#define IDC_POSX                        1009
#define IDC_POSY                        1010
#define IDC_POSZ                        1011
#define IDC_NORMX                       1012
#define IDC_NORMY                       1013
#define IDC_NORMZ                       1014
#define IDC_DIFR                        1015
#define IDC_DIFG                        1016
#define IDC_DIFB                        1017
#define IDC_USEFG                       1018
#define IDC_MASTER                      1018
#define IDC_VERTEXRTL                   1019
#define IDC_PPRTL                       1020
#define IDC_STATNORM0                   1021
#define IDC_STATNORM1                   1022
#define IDC_STATNORM2                   1023
#define IDC_STATNORM3                   1024
#define IDC_INDRB                       1025
#define IDC_FLUX                        1026
#define IDC_DUPLICATE                   1026
#define IDC_DINT                        1027
#define IDC_TABBY                       1028
#define IDC_LIZZIE                      1029
#define IDC_PACKLIST                    1030
#define IDC_PROGRESS                    1033
#define IDC_IMPHELP                     1035
#define IDC_WAITTEXT                    1036
#define IDC_OBJID                       1038
#define IDC_HEIGHT                      1039
#define IDC_WIDTH                       1040
#define IDC_EDIT3                       1041
#define IDC_SEGMENTS                    1042
#define IDC_TAPER                       1043
#define IDC_EDIT5                       1046
#define IDC_PREVIEW                     1047
#define IDC_UNLIT                       1048
#define IDC_RTTRANS                     1049
#define IDC_ALPHA                       1050
#define IDC_TRANSP                      1051
#define IDC_ROT45                       1054
#define IDC_USCL                        1055
#define IDC_SCLAPPLY                    1056
#define IDC_ROT5                        1057
#define IDC_ROT90                       1058
#define IDC_VPAN8                       1059
#define IDC_VPAN64                      1060
#define IDC_VPAN32                      1061
#define IDC_VPAN1                       1062
#define IDC_UPAN8                       1063
#define IDC_UPAN64                      1064
#define IDC_UPAN32                      1065
#define IDC_UPAN1                       1066
#define IDC_VSCL                        1067
#define IDC_SCLRESET                    1068
#define IDC_ROT1                        1069
#define IDC_TEXNAME                     1070
#define IDC_FLIPU                       1071
#define IDC_FLIPV                       1072
#define IDC_ST01                        1073
#define IDC_ST02                        1074
#define IDC_ST03                        1075
#define IDC_ST04                        1076
#define IDC_ST05                        1077
#define IDC_ST06                        1078
#define IDC_ST07                        1079
#define IDC_ST08                        1080
#define IDC_ST09                        1081
#define IDC_ST10                        1082
#define IDC_TEXTSTUFF                   1083
#define IDC_PROGRESSX                   1085
#define IDC_ACTIVE                      1086
#define IDC_DS                          1087
#define IDC_NOLIGHT                     1088
#define IDC_VISIBLE                     1089
#define IDC_PARENT                      1091
#define IDC_SCRIPT                      1092
#define IDC_EDITSCRIPT                  1093
#define IDC_SCX                         1094
#define IDC_SCY                         1095
#define IDC_SCZ                         1096
#define IDC_OPACITY                     1097
#define IDC_ST11                        1098
#define IDC_ST12                        1099
#define IDC_ST13                        1100
#define IDC_ST14                        1101
#define IDC_ST15                        1102
#define IDC_ST16                        1103
#define IDC_ST17                        1104
#define IDC_PROPTREE                    1105
#define IDC_AUTOSZ                      1107
#define IDC_ITEMSX                      1111
#define IDC_TABBER                      1112
#define ID_FILE_OPTIONS                 40001
#define ID_FILE                         40002
#define ID_FILE_SAVEAS                  40004
#define ID_FILE_QUIT                    40006
#define ID_EDIT_DELETE                  40010
#define ID_EDIT_MOVETO                  40012
#define ID_EDIT_SCALETO                 40013
#define ID_EDIT_ROTATETO                40014
#define ID_EDIT                         40015
#define ID_LIGHTING_GLOBALLIGHTINGOPTIONS 40016
#define ID_LIGHTING_RECALCULATELIGHTMAPS 40018
#define ID_LIGHTING                     40019
#define ID_LIGHTING_LIGHTMANAGER        40020
#define ID_LIGHTING_ADDLIGHTSOURCE      40021
#define ID_BRUSH_IMPORTBRUSH            40023
#define ID_SWATCHES_TEXTURESWATCH       40024
#define ID_SWATCHES_SOUNDSWATCH         40025
#define ID_SWATCHES_BRUSHSWATCH         40026
#define ID_SWATCHES_OBJECTSWATCH        40027
#define ID_SWATCHES_COLORSWATCH         40028
#define ID_VIEW_FREEZEALLVIEWPORTS      40029
#define ID_VIEW_SETRASTERLEVEL          40030
#define ID_HELP_VIEWHELP                40032
#define ID_HELP_ABOUTBLUEFIRE           40033
#define ID_DELETE                       40036
#define ID_SETCURRENT                   40037
#define ID_EXPORT                       40038
#define ID_DUPLICATE                    40039
#define ID_USAGE                        40040
#define ID_VIEW_PACKAGEVIEWER           40042
#define ID_EDIT_DESELECTALL             40044
#define ID_VIEW_SURFPROP                40045
#define ID_EDIT_FLIPPOLYGONNORMAL       40046
#define ID_EDIT_ROTPOLYGONNORMAL        40047
#define ID_VIEW_SINGLEVIEW_TL           40048
#define ID_VIEW_SINGLEVIEW_TR           40049
#define ID_VIEW_SINGLEVIEW_BL           40050
#define ID_VIEW_SINGLEVIEW_BR           40051
#define ID_VIEW_QUADVIEW                40052
#define ID_Menu                         40054
#define ID_EDIT_FIXENVNORMALS           40057
#define ID_EDIT_FIXOBJNORMALS           40058
#define ID_EDIT_FIXENVVROT              40061
#define ID_EDIT_FIXOBJVROT              40062
#define ID_VIEW_ACTORBROWSER            40064
#define ID_EDIT_ALIGNTEXTURES           40065
#define ID_CONTEXT_PROPERTIES           40066
#define ID_CONTEXT_ALIGNTEXTURES        40067
#define ID_CONTEXT_AUTO                 40068
#define ID_Menu40069                    40069
#define ID_TEXTURES_ALIGN               40070
#define ID_TEXTURES_AUTO                40071
#define ID_CONTEXT_SELECTION            40072
#define ID_SELECTION_SELECTADJACENT     40073
#define ID_Menu40075                    40075
#define ID_CONTEXT_ADDHERE              40076
#define ID_ADDHERE_LIGHT                40077
#define ID_ADDHERE_ACTOR                40078
#define ID_ADDHERE_BRUSH                40079
#define ID_CONTEXT_DELETE               40080
#define ID_CONTEXT_CLONE                40081
#define ID_CONTEXT_DESELECTALL          40082
#define ID_SELECTION_COPLANAR           40083

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40084
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
